language: c
dist: bionic

env:
    - SMVERSION=1.8  COMPILER_PARAMS=""
    - SMVERSION=1.8  COMPILER_PARAMS="_GMX_DEBUG=1"
    - SMVERSION=1.9  COMPILER_PARAMS=""
    - SMVERSION=1.9  COMPILER_PARAMS="_GMX_DEBUG=1"
    - SMVERSION=1.10 COMPILER_PARAMS=""
    - SMVERSION=1.10 COMPILER_PARAMS="_GMX_DEBUG=1"
    - SMVERSION=1.11 COMPILER_PARAMS=""
    - SMVERSION=1.11 COMPILER_PARAMS="_GMX_DEBUG=1"

matrix:
    fast_finish: true
    allow_failures:
    - env: SMVERSION=1.8  COMPILER_PARAMS=""
    - env: SMVERSION=1.8  COMPILER_PARAMS="_GMX_DEBUG=1"
    - env: SMVERSION=1.9  COMPILER_PARAMS=""
    - env: SMVERSION=1.9  COMPILER_PARAMS="_GMX_DEBUG=1"

before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib
    - sudo apt-get install lib32stdc++6

before_script:
    # Make directory for SourceMod
    - mkdir -p am/sm
    - cd am/sm
    - wget -q "http://www.sourcemod.net/latest.php?version=$SMVERSION&os=linux" -O sourcemod.tar.gz
    - tar -xzf sourcemod.tar.gz

    # Download git-helper script for generating defines, start him.
    - wget -q https://raw.githubusercontent.com/CrazyHackGUT/sm-plugins/master/git.sh
    - chmod +x git.sh
    - ./git.sh > addons/sourcemod/scripting/GameX.git.sp

    # Go to scripting directory, exec chmod
    - cd addons/sourcemod/scripting
    - chmod +x spcomp
    - chmod +x compile.sh

    # Copy plugins, download dependencies
    - cp -Rf ${TRAVIS_BUILD_DIR}/scripting/* ./
    - mkdir -p include/ripext
    - curl "https://raw.githubusercontent.com/ErikMinekus/sm-ripext/master/pawn/scripting/include/ripext.inc" -o include/ripext.inc
    - curl "https://raw.githubusercontent.com/ErikMinekus/sm-ripext/master/pawn/scripting/include/ripext/http.inc" -o include/ripext/http.inc
    - curl "https://raw.githubusercontent.com/ErikMinekus/sm-ripext/master/pawn/scripting/include/ripext/json.inc" -o include/ripext/json.inc
    - mkdir -p GameX

script:
    - ./spcomp $COMPILER_PARAMS GameX.git.sp GameX.sp -E -oGameX/Core
    - ./spcomp $COMPILER_PARAMS GameX.git.sp GameX_PlayerManager.sp -E -oGameX/PlayerManager
    - ./spcomp $COMPILER_PARAMS GameX.git.sp GameX_ServerInformation.sp -E -oGameX/ServerInformation

before_deploy:
    - export CUSTOM_POSTFIX=_$SMVERSION
    - if [ "$COMPILER_PARAMS" ]; then export CUSTOM_POSTFIX=$CUSTOM_POSTFIX"_debug"; fi
    - mkdir -p $TRAVIS_BUILD_DIR/../$SFTP_SOURCE_DIRECTORY/addons/sourcemod/{configs/GameX,scripting,plugins/GameX,data/gmx/cache,translations}
    - cp -Rf $TRAVIS_BUILD_DIR/scripting/* $TRAVIS_BUILD_DIR/../$SFTP_SOURCE_DIRECTORY/addons/sourcemod/scripting/
    - cp -Rf $TRAVIS_BUILD_DIR/translations/* $TRAVIS_BUILD_DIR/../$SFTP_SOURCE_DIRECTORY/addons/sourcemod/translations/
    - cp -Rf $TRAVIS_BUILD_DIR/configs/GameX/* $TRAVIS_BUILD_DIR/../$SFTP_SOURCE_DIRECTORY/addons/sourcemod/configs/GameX/
    - cp -Rf GameX/* $TRAVIS_BUILD_DIR/../$SFTP_SOURCE_DIRECTORY/addons/sourcemod/plugins/GameX
    - cd $TRAVIS_BUILD_DIR
    - wget --user=$HTTP_USER --password=$HTTP_PASSWORD $BASE_URL/travis.sh
    - touch $TRAVIS_BUILD_DIR/../$SFTP_SOURCE_DIRECTORY/addons/sourcemod/data/gmx/cache/.keep

deploy:
    - provider: script
      skip_cleanup: true
      script: bash travis.sh